MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE: "R-101-C4"
  RPN:
    PRE_NMS_TOP_N_TRAIN: 1200
    PRE_NMS_TOP_N_TEST: 600
    POST_NMS_TOP_N_TRAIN: 100
    POST_NMS_TOP_N_TEST: 100
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("mosquitoes_cocostyle_CEFET_train",)
  TEST: ("mosquitoes_cocostyle_CEFET_test",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: "./results/e2e_faster_rcnn_R_101_C4_1x_cocostyle"
