MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "results/aug/e2e_faster_rcnn_R_50_C4_1x_cocostyle_blend/model_final.pth"
  RPN:
    PRE_NMS_TOP_N_TRAIN: 600
    PRE_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 50
    POST_NMS_TOP_N_TEST: 50
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
DATASETS:
  TRAIN: ("mosquitoes_cocostyle_blend_train",)
  TEST: ("mosquitoes_cocostyle_noaug_rectified_DJI_0033", "mosquitoes_cocostyle_noaug_rectified_DJI_0038", "mosquitoes_cocostyle_noaug_rectified_DJI_0043",)
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 4
OUTPUT_DIR: "./results/aug/e2e_faster_rcnn_R_50_C4_1x_cocostyle_blend"
INPUT:
  FLIP_PROB_TRAIN: 0.0
